---
- hosts: jenkins-slaves
  vars:
    maven_url: "http://mirror.nexcess.net/apache/maven/maven-3/3.2.1/binaries/apache-maven-3.2.1-bin.tar.gz"
    ant_url: "http://www.dsgnwrld.com/am//ant/binaries/apache-ant-1.9.4-bin.tar.gz"
    j_home: "/home/jenkins"
    t_home: /home/jenkins/tools
    m_home: /home/jenkins/tools/maven
    a_home: /home/jenkins/tools/ant

  tasks:
    - include: tasks/setup_user.yml
    - include: tasks/install_tools.yml
    - include: tasks/install_jdk.yml
    - include: tasks/install_libraries.yml
    - include: tasks/update_configs.yml

