---
  - name: Install_svn-1.6 | update source.list
    sudo: yes
    sudo_user: root
    copy: src=sources.list dest=/etc/apt/sources.list

  - name: "Installing Libraries"
    sudo: yes
    sudo_user: root
    apt: pkg={{item}} update_cache=yes state=latest
    with_items:
      - asciidoc
      - autoconf
      - automake
      - build-essential
      - cmake
      - curl
      - git-core
      - dh-make
      - debhelper
      - devscripts
      - g++-multilib
      - gcc-multilib
      - lib32z1
      - lib32ncurses5
      - lib32bz2-1.0
      - libc6-dev-i386
      - libcppunit-dev
      - libcurl4-nss-dev
      - libcurl4-openssl-dev
      - libfuse-dev
      - libjpeg8-dev
      - liblzo2-dev
      - libsasl2-dev
      - libsnappy-dev
      - libssl-dev
      - libtool
      - libz-dev
      - pkg-config
      - protobuf-compiler
      - python-boto
      - python-dev
      - sharutils
      - g++-4.8-multilib
      - libstdc++-4.8-dev
