---
- name: Install_svn-1.6 | remove svn 1.8
  sudo: yes
  sudo_user: root
  apt: pkg={{item}} state=absent
  with_items:
    - libsvn1
    - python-svn

- name: Install_svn-1.6 | downgrade source.list 
  sudo: yes
  sudo_user: root
  copy: src=subversion.list dest=/etc/apt/sources.list

- name: Install_svn-1.6 | downgrade svn-1.6
  sudo: yes
  sudo_user: root
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - libsvn1
    - python-svn
    - subversion

- name: Install_svn-1.6 | update source.list 
  sudo: yes
  sudo_user: root
  copy: src=sources.list dest=/etc/apt/sources.list
