---
- name: Install_svn-1.6 | remove svn 1.8
  sudo: yes
  sudo_user: root
  apt: pkg={{item}} state=absent
  with_items:
    - libsvn1=1.8*
    - python-svn=1.7.8*

- name: Install_svn-1.6 | downgrade source.list 
  sudo: yes
  sudo_user: root
  copy: src=subversion.list dest=/etc/apt/sources.list

- name: Install_svn-1.6 | downgrade svn-1.6
  sudo: yes
  sudo_user: root
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - libsvn1=1.6*
    - python-svn=1.7.5*
    - subversion=1.6*

- name: Install_svn-1.6 | update source.list 
  sudo: yes
  sudo_user: root
  copy: src=sources.list dest=/etc/apt/sources.list
