---
  - name: install tools | setup tools dir
    sudo: yes
    sudo_user: jenkins
    file: path={{tools_home}} state=directory owner=jenkins group=jenkins mode=0775


  - name: install tools | setup ant maven forrest tools dir
    sudo: yes
    sudo_user: jenkins
    file: path={{tools_home}}/{{item}} state=directory owner=jenkins group=jenkins mode=0775
    with_items:
      - ant
      - maven
      - forrest

  - name: install tools | download maven
    sudo: yes
    sudo_user: jenkins
    get_url: url={{maven_url}} dest={{tools_home}}/maven/maven.tar.gz mode=0775

  - name: install tools | download maven
    sudo: yes
    sudo_user: jenkins
    get_url: url={{ant_url}} dest={{tools_home}}/ant/ant.tar.gz mode=0775

  - name: install tools | download forrest
    sudo: yes
    sudo_user: jenkins
    get_url: url={{forrest_url}} dest={{forrest_home}}/forrest.tar.gz mode=775

  - name: install tools | untar maven
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{maven_home}}/maven.tar.gz dest={{tools_home}}/maven

  - name: install tools | untar ant
    sudo: yes
    sudo_user: jenkins
    unarchive: copy=no src={{ant_home}}/ant.tar.gz dest={{tools_home}}/ant

  - name: install tools | symlink maven -> latest
    sudo: yes
    sudo_user: jenkins
    file: src=apache-maven-{{maven_version}} dest={{maven_home}}/latest state=link

  - name: install tools | symlink ant -> latest
    sudo: yes
    sudo_user: jenkins
    file: src=apache-ant-{{ant_version}} dest={{ant_home}}/latest state=link

  - name: install tools | cleanup remains 
    sudo: yes
    sudo_user: jenkins
    file: path={{tools_home}}/{{item}} state=absent
    with_items:
      - ant/ant.tar.gz
      - maven/maven.tar.gz
      - forrest/forest.tar.gz
