---
  - name: update_configs | limits.conf
    sudo: yes
    sudo_user: root
    copy: src=limits.conf dest=/etc/security/limits.conf

  - name: update_configs | settings.xml
    sudo: yes
    sudo_user: jenkins
    template: src=m2_settings.j2 dest={{m2_cache_dir}}/settings.xml
               owner=jenkins group=jenkins 
    when: m2_settings
